src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $sujet = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?bool $is_read = false;

    #[ORM\ManyToOne(inversedBy: 'sent')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sender = null;

    #[ORM\ManyToOne(inversedBy: 'destinataire')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $destinataire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function isIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getDestinataire(): ?User
    {
        return $this->destinataire;
    }

    public function setDestinataire(?User $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;


use App\Entity\Messages;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('sujet', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('destinataire', EntityType::class, [
                "class" => User::class,
                "choice_label" => "pseudo",
                "attr" => [
                    "class" => "form-control"
                ]
            ])

            ->add('envoyer', SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-primary"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use App\Repository\MessagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\Query\Expr\OrderBy;

class MessageController extends AbstractController
{
    private $entityManager;
    private $messagesRepository;

    public function __construct(EntityManagerInterface $entityManager, MessagesRepository $messagesRepository)
    {
        $this->entityManager = $entityManager;
        $this->messagesRepository = $messagesRepository;
    }

    #[Route('/message', name: 'app_message')]
    public function index(): Response
    {
        return $this->redirectToRoute('messagerie');
    }

    /**
     * @Route("/send", name="send")
     */
    public function send(): Response
    {
        // Vérifier si l'utilisateur est connecté
        if ($this->getUser()) {
            $messages = $this->getUser()->getSent();

            return $this->render('message/send.html.twig', [
                'messages' => $messages,
            ]);
        } else {
            // Utilisateur non authentifié, afficher le message d'erreur
            return $this->render('message/error.html.twig', [
                'errorMessage' => "Vous devez vous authentifier pour accéder à cette page.",
            ]);
        }
    }
    /**
     * @Route("/messagerie", name="messagerie")
     */
    public function messagerie(Request $request): Response
    {
        $destinataireMessages = $this->entityManager
            ->getRepository(Messages::class)
            ->findBy(
                ['destinataire' => $this->getUser()],
                ['created_at' => 'DESC']
            );

        $message = new Messages();
        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setSender($this->getUser());
            $this->entityManager->persist($message);
            $this->entityManager->flush();
            $this->addFlash("message", "Message envoyé avec succès.");

            return $this->redirectToRoute('messagerie');
        }

        return $this->render('message/messagerie.html.twig', [
            'messages' => $destinataireMessages,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/message/{id}", name="read")
     */
    public function read($id): Response
    {
        $message = $this->entityManager->getRepository(Messages::class)->find($id);

        if (!$message) {
            throw $this->createNotFoundException('Le message n\'existe pas.');
        }

        $message->setIsRead(true);
        $this->entityManager->flush();

        return $this->render('message/read.html.twig', [
            'message' => $message,
        ]);
    }

    /**
     * @Route("/repondre/{id}", name="repondre")
     */
    public function repondre(Request $request, $id): Response
    {
        $message = $this->entityManager->getRepository(Messages::class)->find($id);

        if (!$message) {
            throw $this->createNotFoundException('Le message n\'existe pas.');
        }

        $repondreForm = $this->createForm(MessagesType::class);

        $repondreForm->handleRequest($request);
        if ($repondreForm->isSubmitted() && $repondreForm->isValid()) {
            // Traiter les données du formulaire et effectuer les actions appropriées

            return $this->redirectToRoute('messagerie');
        }

        return $this->render('message/reponsemessage.html.twig', [
            'message' => $message,
            'repondreForm' => $repondreForm->createView(),
        ]);
    }

    /**
     * @Route("/formulaire", name="formulaire")
     */
    public function formulaire(Request $request, ?string $destinatairePseudo): Response
    {
        $user = $this->getUser(); // Récupérer l'utilisateur actuellement connecté
        $message = new Messages();
        $message->setSender($user); // Affecter l'expéditeur

        if ($destinatairePseudo) {
            // Utiliser $recipientPseudo pour rechercher le destinataire et affecter le destinataire à $message->setRecipient()
            // ...
        }

        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($message);
            $this->entityManager->flush();

            // Traiter les données du formulaire et effectuer les actions appropriées

            return $this->redirectToRoute('messagerie');
        }

        return $this->render('message/formulaire.html.twig', [
            'form' => $form->createView(),
            'message' => $message, // Ajoutez la variable 'message' ici
        ]);
    }

    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        // Vérifier si l'utilisateur est authentifié
        if ($this->getUser()) {
            $messages = $this->getUser()->getDestinataire();
            return $this->render('message/received.html.twig', [
                'messages' => $messages,
            ]);
        } else {
            // Utilisateur non authentifié, afficher le message d'erreur
            return $this->render('message/error.html.twig', [
                'errorMessage' => "Vous devez vous authentifier pour accéder à cette page.",
            ]);
        }
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $this->entityManager->remove($message);
        $this->entityManager->flush();

        return $this->redirectToRoute("received");
    }

    /**
     * @Route("/navbar", name="navbar")
     */
    public function navbar($id): Response
    {
        $message = $this->entityManager->getRepository(Messages::class)->find($id);

        if (!$message) {
            throw $this->createNotFoundException('Le message n\'existe pas.');
        }

        $message->setIsRead(true);
        $this->entityManager->flush();

        return $this->render('message/read.html.twig', [
            'message' => $message,
        ]);
    }
}

templates/message/error.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
   <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
{% endblock %}

templates/message/formulaire.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}

    {% if is_granted('ROLE_USER') %}
        <div class="container">
            <div class="row">
                <div class="col-2"></div> {# Marge à gauche #}
                <div class="col-8">
                    {# Affiche un message de bienvenue avec le pseudo de l'utilisateur connecté #}
                    <p class="text-secondary mt-6">Bonjour {% if app.user %}
                        {{ app.user.pseudo }}
                        {% endif %}, bienvenue dans ta boîte d'envoi</p>
                </div>
                <div class="col-2"></div> {# Marge à droite #}
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-2"></div> {# Marge à gauche #}
                <div class="col-8 text-end">
                    {# Affiche un lien de retour vers la messagerie avec la route 'messagerie' #}
                    <a class="btn btn-secondary mr-2 text-light " href="{{ path('messagerie') }}">Retour à la messagerie</a>
                </div>
                <div class="col-2"></div> {# Marge à droite #}
            </div>
        </div>
        <br>
        <div class="mt-6"></div>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-2 col-1"></div> {# Marge à gauche #}
                <div class="col-md-8 col-10 border border-primary">
                    {# Affiche un formulaire d'envoi avec le formulaire 'form' #}
                    <h4>Formulaire d'envoi</h4>
                    {{ form_start(form) }}

                    {# Champ caché pour le destinataire par défaut, basé sur le paramètre userId de la requête #}
                    {{ form_row(form.destinataire, {'value': app.request.get('userId')}) }}

                    {{ form_widget(form) }}
                    {{ form_end(form) }}

                    <br> {# Saut de ligne ajouté ici #}
                </div>
                <div class="col-md-2 col-1"></div> {# Marge à droite #}
            </div>
        </div>

        <div class="mt-6"></div>

        <div class="container">
            <div class="row">
                <div class="col-2"></div> {# Marge à gauche #}
                <div class="col-8 text-end">
                    {# Affiche un contenu optionnel (manquant dans le code fourni) #}
                </div>
                <div class="col-2"></div> {# Marge à droite #}
            </div>
        </div>

        <div class="mt-6"></div>
    {% else %}
       <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}

    <br>

{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/index.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <div class="row">
            <div class="mt-3"></div> {# Marge en haut #}
            <div class="col-1"></div> {# Colonne de marge #}
            <div class="col-11">
                <h1 class="text-secondary mt-6">Messagerie</h1> {# Titre de la page #}
            </div>
        </div>

        <div class="mt-6"></div> {# Marge en haut #}

        <div class="container text-center">
            <div class="row">
                <div class="col-4 border border-primary">
                    <h4>Message reçu</h4> {# Titre pour la section des messages reçus #}
                    <div class="mt-3"></div> {# Marge en haut #}
                    <div class="d-flex justify-content-between align-items-center">
                        <p>pseudo</p> {# Affiche un pseudo de l'utilisateur #}
                        <a href="{{ path('received') }}">
                            <img src="{{ asset('img/messageDebugTonCodemini.png') }}" alt="boîte de réception" class="d-block mx-auto img-fluid">
                        </a> {# Lien vers la page des messages reçus avec une icône #}
                        <a href="{{ path('received') }}">
                            <img src="{{ asset('img/supprimemessagemini.png') }}" alt="Supprimer le message" class="d-block mx-auto img-fluid">
                        </a> {# Lien pour supprimer le message avec une icône #}
                    </div>
                </div>
                <div class="col-8 border border-primary">col-8 {# Colonne pour le contenu des messages #}
                </div>
            </div>
        </div>
    {% else %}
      <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/messagerie.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <div class="container">
            <div class="row">
                <div class="col-9">
                    {# Affiche un message de bienvenue avec le pseudo de l'utilisateur connecté #}
                    <p class="text-secondary mt-6 {{ app.user ? 'h4' : 'h1' }} mb-3"> Bonjour {% if app.user %}
                        {{ app.user.pseudo }}
                    {% endif %}, bienvenue dans ta messagerie</p>
                </div>
            </div>
        </div>
        <div class="mt-3"></div> {# Marge en haut #}
        <div class="row">
            <div class="col-12 col-md-8">
                <!-- Messages reçus -->
                <div class="text-start text-md-end">
                    <a class="btn btn-primary mr-2 mb-2 mb-md-0 ml-2 text-light" href="{{ path('received') }}">Messages reçus
                        <span class="badge badge">{{ app.user.destinataire|length }}</span>
                    </a>
                    <a class="btn btn-secondary mr-2 ml-2 text-light" href="{{ path('send') }}">Messages envoyés
                        <span class="badge badge">{{ app.user.sent|length }}</span>
                    </a>
                </div>
            </div>
        </div>

        <div class="mt-6"></div> {# Marge en haut #}

        <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="mt-6"></div>
                    <p class="text-secondary mt-6">Message reçu</p>
                    {% if messages is empty %}
                        <p class="text-secondary mt-6">Aucun message reçu.</p> {# Affiche un message si aucune message n'est reçu #}
                    {% else %}
                        <ul>
                            {# Affiche la liste des messages reçus #}
                            {% for message in messages %}
                                {# Ajoute une classe 'fw-bold' au message non lu #}
                                {% set bold = message.isIsRead ? "" : "fw-bold" %}
                                <li class="d-flex flex-wrap align-items-center" style="margin-bottom: 10px;"> {# Ajoute une marge en bas de 10px #}
                                    <div class="col-12 col-md-3 {{ bold }} mb-2 mb-md-0">
                                        <a href="{{ path('read', {id: message.getId()}) }}">
                                            {# Affiche une icône différente pour les messages lus et non lus #}
                                            <img src="{{ message.isIsRead ? asset('img/messageDebugTonCodemini.png') : asset('img/messageDebugTonCodenonlu.png') }}" alt="Voir message" class="d-block mx-auto img-fluid">
                                        </a>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <span style="list-style-type: none;">{{ message.sender.pseudo }}</span>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="col-8">
                    <div class="mt-6"></div>
                    <p class="text-secondary mt-6">Écrire un message</p>
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col">
                            <p><strong>De:</strong> {{ app.user.pseudo }}</p>
                        </div>
                        <div class="col">
                            {# Champ pour le destinataire avec une classe de style #}
                            {{ form_row(form.destinataire, {'label': 'À', 'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    {# Rendu des champs du formulaire #}
                    {{ form_row(form.sujet, {'attr': {'class': 'form-control'}}) }}
                    {{ form_row(form.message, {'attr': {'class': 'form-control'}}) }}
                    {{ form_row(form.envoyer, {'attr': {'class': 'btn btn-primary'}}) }}
                    {{ form_end(form) }}
                    <div class="mt-6"></div> {# Marge en haut #}
                </div>
            </div>
        </div>
        <br>
        <div class="mt-6"></div> {# Marge en haut #}
    {% else %}
      <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/read.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <div class="container">
            <div class="row mt-3">
                <div class="col-1"></div> {# Colonne de marge #}
                <div class="col-11">
                    {# Affiche le pseudo de l'expéditeur et la date du message formatée #}
                    <p class="text-secondary mt-6">Message reçu de : {{ message.sender.pseudo }} le {{ message.createdAt|date('j F Y H:i', 'Europe/Paris', 'fr') }}</p>
                </div>
            </div>

            <div class="row mt-6">
                <div class="col-11">
                    {# Affiche le sujet du message #}
                    <p class="lead text-secondary text-center">Sujet : {{ message.sujet }}</p>
                </div>
            </div>

            <div class="row mt-6">
                <div class="col-12">
                    {# Affiche le contenu du message #}
                    <p class="lead text-secondary text-center">Message : {{ message.message }}</p>
                </div>
            </div>

            <div class="row mt-6">
                <div class="col-12 text-center">
                    {# Lien pour répondre au message avec une icône de bouton #}
                    <a class="btn btn-primary mr-2 mb-2" href="{{ path('formulaire', { 'id': message.sender.id }) }}">Répondre</a>
                    {# Lien pour retourner à la liste des messages avec une icône de bouton #}
                    <a class="btn btn-secondary mr-2 mb-2" href="{{ path('app_message') }}">Retour</a>
                    <br> {# Saut de ligne #}
                </div>
            </div>
        </div>
    {% else %}
      <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/received.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <h1 class="text-secondary mt-6">Messages reçus</h1> {# Titre de la page #}
                </div>
            </div>
        </div>

        <div class="mt-3"></div> {# Marge en haut #}

        <div class="container">
            <div class="row">
                <div class="col-8 text-end">
                    <a class="btn btn-secondary text-light" onclick="goBack()">Retour</a> {# Lien de retour avec une icône de bouton #}
                    <div class="mt-6"></div> {# Marge en haut #}
                </div>
            </div>
        </div>

        <div class="mt-6"></div> {# Marge en haut #}

        <section class="container">
            <div class="row">
                <div class="col-3">De</div>
                <div class="col-3">Sujet</div>

                <div class="col-2">Date</div>
                <div class="col-1">Action</div>
            </div>

            <div class="mt-3"></div> {# Marge en haut #}

            {% for message in app.user.destinataire|sort((a, b) => b.createdAt <=> a.createdAt) %}
                {% if message.isRead == 0 %}
                    {% set bold = "fw-bold" %}
                {% else %} 
                    {% set bold = "" %}
                {% endif %} 

                <div class="row">
                    <div class="col-3 {{ bold }}">{{ message.sender.pseudo }}</div>
                    <div class="col-3 {{ bold }}">
                        <a href="{{ path('read', { 'id': message.id }) }}">
                            {{ message.sujet[:10] }}{# Affiche les 10 premiers caractères du sujet #}
                        </a>
                    </div>

                    <div class="col-2 {{ bold }}">{{ message.createdAt|date('d F Y H:i', 'Europe/Paris') }}</div>

                    <div class="col-1">
                        <a href="{{ path('delete', { 'id': message.id }) }}">
                            <img src="{{ asset('img/supprimemessagemini.png') }}" alt="Supprimer">
                        </a>
                    </div>
                </div>

                <div class="mt-3"></div> {# Marge en haut #}
            {% endfor %}
        </section>

        <div class="mt-6"></div> {# Marge en haut #}

        <script>
            function goBack() {
                window.history.back(); {# Fonction pour revenir en arrière dans l'historique du navigateur #}
            }
        </script>
    {% else %}
       <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/repondre.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Répondre au message{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <h1>Répondre au message</h1> {# Titre de la page #}

        <p>Destinataire : {{ message.sender.username }}</p> {# Affiche le nom d'utilisateur du destinataire #}

        <div class="container">
            <div class="row">
                <div class="col-md-8 col-12 border border-primary">
                    <h4>Répondre au message reçu</h4> {# Titre de la section #}
                    {{ form_start(form) }} {# Début du formulaire #}
                    {{ form_widget(form) }} {# Affiche les champs du formulaire #}
                    {{ form_end(form) }} {# Fin du formulaire #}
                </div>
            </div>
        </div>
    {% else %}
      <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/reponsemessage.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Répondre au message{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <h1>Répondre au message</h1> {# Titre de la page #}

        <p>Destinataire : {{ message.sender.username }}</p> {# Affiche le nom d'utilisateur du destinataire #}

        <div class="container">
            <div class="row">
                <div class="col-md-8 col-12 border border-primary">
                    <h4>Répondre au message</h4> {# Titre de la section #}
                    {{ form_start(repondreForm) }} {# Début du formulaire #}
                    {{ form_widget(repondreForm) }} {# Affiche les champs du formulaire #}
                   
                    {{ form_end(repondreForm) }} {# Fin du formulaire #}
                </div>
            </div>
        </div>
    {% else %}
       <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}

templates/message/send.html.twig
{# Étend le template de base appelé 'base.html.twig' #}
{% extends 'base.html.twig' %}

{# Définit le contenu de la balise <title> de la page #}
{% block title %}Messagerie{% endblock %}

{# Début du bloc principal du corps de la page #}
{% block body %}
    {% if is_granted('ROLE_USER') %}
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <h1 class="text-secondary mt-6">Messages envoyés</h1> {# Titre de la page #}
                </div>
            </div>
        </div>

        <div class="mt-3"></div>

        <div class="container">
            <div class="row">
                <div class="col-8 text-end">
                    <a class="btn btn-secondary text-light" onclick="goBack()">Retour</a> {# Bouton de retour #}
                    <div class="mt-3"></div>
                </div>
            </div>
        </div>

        <div class="mt-6"></div>

        <section class="container">
            <div class="row">
                <div class="col-3">A</div> {# Colonnes du tableau #}
                <div class="col-3">Sujet</div>
               
                <div class="col-2">Date</div>
                <div class="col-1">Action</div>
            </div>

            <div class="mt-3"></div>

            {% for message in app.user.sent|sort((a, b) => b.createdAt <=> a.createdAt) %}
                {% if message.isRead == 0 %}
                    {% set bold = "fw-bold" %} {# Si le message n'est pas lu, appliquer la classe CSS "fw-bold" pour mettre en gras #}
                {% else %} 
                    {% set bold = "" %} {# Sinon, ne pas appliquer de style gras #}
                {% endif %} 

                <div class="row">
                    <div class="col-3 {{ bold }}">{{ message.destinataire.pseudo }}</div> {# Nom du destinataire du message #}
                    <div class="col-3 {{ bold }}">
                        <a href="{{ path('read', { 'id': message.id }) }}">{{ message.sujet [:10]}}</a> {# Lien vers la lecture du message #}
                    </div>
                   
                    <div class="col-2 {{ bold }}">{{ message.createdAt|date('d F Y H:i', 'Europe/Paris') }}</div> {# Date du message formatée #}

                    <div class="col-1">
                        <a href="{{ path('delete', { 'id': message.id }) }}">
                            <img src="{{ asset('img/supprimemessagemini.png') }}" alt="Supprimer"> {# Lien pour supprimer le message #}
                        </a>
                    </div>
                </div>

                <div class="mt-3"></div>
            {% endfor %}
        </section>

        <div class="mt-6"></div>

        <script>
            function goBack() {
                window.history.back();
            }
        </script>
    {% else %}
     <div class="text-center">
       <p class="text-secondary">Vous devez vous authentifier pour accéder à cette page.</p>
   </div>
    {% endif %}
{# Fin du bloc principal du corps de la page #}
{% endblock %}